### ISSUE TITLE
Minimum pass count

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-plus#3]
Currently only an exact number of tests passing is allowed.

When running tests on lots of arch and platforms and py versions, usually the number varies a bit.

Either a new envvar for minimum, or another "variance" envvar to determine +/- how many is allowable.

**Comment by ssbarnea** [comment]
The exact match is by design and there is a good reason for it. If it would not be like this, in time people will add new tests without updating the expected runs. Later if some of these tests are disabled or skipped by "mistake", CI/CD pipeline would not be able to complain.

For this reason this feature is feasible only if you mention an exact match, and the values are likely to be configured in CI job definitions, not the tox.ini file. Only the CI job knows exactly in which environment will run and how many tests are expected to pass.

If you would try to store the expected number in tox.ini, you will, sooner or later, reach a point where on a developer machine some tests are skipped, for good reasons. In that case the execution will fail, which is not desired.

I hope this answers why it was implemented like this. Probably I will need to improve the README to add these.

**Comment by jayvdb** [comment]
I am wanting to use it in OBS, for distro packaging, and we do not use tox.ini, and we do not allow having unnecessary stuff in the .spec files, such as fiddling with multiple values for an envvar based on arch.

Most rpm version updates are automated, and changing hard coded uncompromising numbers cant be automated.

I want to use it to ensure that new versions do not slip passed CI with *less* tests passing.  Bumping up the minimum is then a task that can be done occasionally when a human notices it.

If you wont allow this feature, I cant use it.  It is that simple.

Your use case is very reasonable , but this feature can be added without breaking your use case.

**Comment by ssbarnea** [comment]
While I think you use-case is flawed and destroys most of benefits of this feature (as you will catch only a particular subset of test coverage issues), I will accept a PR that adds ability to use a range. I think that using a string lie `PYTEST_REQPASS=100,120` or `PYTEST_REQPASS=">=100,<200"` could be seen acceptable.

Another alternative would be to just copy the plugin code and tune it to match you special use-case. In the end this is one of the shortest pytest plugins ever written and you can just copy https://github.com/pytest-dev/pytest-plus/blob/master/pytest_plus/__init__.py to your `conftest.py`.
